In [142]:
import pandas as pd
import numpy as np

# Dataset link
<ul>      
        <li>Bankwise ATM/POS/Card Statistics from March 22 - April 26</li>
        <li>Source = https://rbi.org.in/Scripts/ATMView.aspx</li>
        <li>All India and State/UT-wise Factsheets of National Family Health Survey  2019-2021</li>
        <li>Source = https://www.data.gov.in/resource/all-india-and-stateut-wise-factsheets-national-family-health-survey-nfhs-5-2019-2021</li>
        <li>Telecom Subscription</li>
        <li>Source https://www.trai.gov.in/release-publication/reports/telecom-subscriptions-reports</li>

</ul>

In [143]:
df_connection = pd.read_csv("../dataset/raw/connection.csv")
df_datafile = pd.read_csv("../dataset/raw/datafile.csv")
df_rbi = pd.read_excel("../dataset/raw/RBI_data.xlsx", sheet_name="data")
df_telecom_sub = pd.read_csv("../dataset/raw/telecom_subscription.csv")

In [144]:
df_connection

    sr.no             telecom_circle  rural_exchanges  connection_provided
0     1.0                      A & N             45.0                405.0
1     2.0  Andhra Pradesh/ Telangana           2665.0              59647.0
2     3.0                      Assam            429.0               5067.0
3     4.0                      Bihar           1000.0               6817.0
4     5.0               Chhattisgarh            449.0               6743.0
5     6.0                    Chennai            123.0               5230.0
6     7.0                    Gujarat           1988.0              34315.0
7     8.0                    Haryana            805.0              21012.0
8     9.0           Himachal Pradesh            811.0               8188.0
9    10.0            Jammu & Kashmir            209.0               3057.0
10   11.0                  Jharkhand            291.0               3872.0
11   12.0                  Karnataka           2217.0              20464.0
12   13.0                     Kerala           1143.0             228741.0
13   14.0             Madhya Pradesh           1982.0              25216.0
14   15.0                Maharashtra           4353.0              44200.0
15    NaN                        NaN              NaN                  NaN
16    NaN                        NaN              NaN                  NaN
17    NaN                 31.01.2015              NaN                  NaN

In [145]:
df_datafile.head()

,States/UTs,Area,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Women (age 15-49 years) having a bank or savings account that they themselves use (%),Women (age 15-49 years) having a mobile phone that they themselves use (%),Women age 15-24 years who use hygienic methods of protection during their menstrual period26 (%),Ever-married women age 18-49 years who have ever experienced spousal violence27 (%),Ever-married women age 18-49 years who have experienced physical violence during any pregnancy (%),Young women age 18-29 years who experienced sexual violence by age 18 (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,India,Urban,160138,179535,26420,82.5,23.1,985.0,924,93.3,...,80.9,69.4,89.4,24.2,2.5,1.1,5.4,28.8,0.6,16.5
1,India,Rural,476561,544580,75419,66.8,28.1,1037.0,931,87.5,...,77.4,46.6,72.3,31.6,3.4,1.6,10.5,42.7,1.6,19.9
2,India,Total,636699,724115,101839,71.8,26.5,1020.0,929,89.1,...,78.6,54,77.3,29.3,3.1,1.5,8.9,38.0,1.3,18.8
3,Andaman & Nicobar Islands,Urban,527,557,85,86.5,22.7,1023.0,941,96.9,...,88.5,80.8,98.5,23.2,0,1.4,15.0,44.7,0.7,33.8
4,Andaman & Nicobar Islands,Rural,2097,1840,282,81.8,19.7,929.0,891,97.8,...,89.8,80.9,99.1,13.2,0.5,2.2,41.1,66.4,7.6,41.9

In [146]:
df_rbi.head()

,Sr no,Number of transaction,Date,Onsite_ATMs,Offsite_ATMs,PoS_Terminals,Micro_ATMs,Bharat_QR_Codes,UPI_QR_Codes,Credit_Cards_Outstanding,...,CC_PoS_Value_000Rs,DC_PoS_Value_000Rs,DC_Ecommerce_Volume,DC_Ecommerce_Value_000Rs,DC_Other_Volume,DC_Other_Value_000Rs,DC_ATM_Withdrawal_Volume,DC_ATM_Withdrawal_Value_000Rs,DC_PoS_Cash_Withdrawal_Volume,DC_PoS_Cash_Withdrawal_Value_000Rs
0,1,63,2026-04-01,136126,73857,11446998,1367989,5616038,770811461,119436129,...,738488494,243434366,25662638,124651148,74041,1682311,413006692,2312062478,8094,15112
1,2,64,2026-03-01,135638,73693,11769361,1389878,5633027,761217394,118633677,...,784704542,243464508,26307005,134339503,78017,1679903,443999321,2484190349,9984,17029
2,3,64,2026-02-01,135004,73830,11664877,1389518,5897360,754203742,117704486,...,674354050,218617996,22661665,111099285,73930,1628965,414511705,2302417305,10737,16749
3,4,64,2026-01-01,134085,73830,11545210,1391526,5843742,738380380,116652407,...,759878304,255130179,24429856,122790555,80114,1646178,441200393,2391720254,12351,1900
4,5,64,2025-12-01,133729,73756,11474672,1414547,5890220,731365285,115791713,...,784764839,245990962,25407654,125123230,81047,1629609,444401793,2389248011,11876,19589

In [147]:
df_telecom_sub.head()

,date,Urban,Rural,Urban_Wireless,Rural_Wireless,Urban_Wireline,Rural_Wireline,Total(million)
0,Jan-15,575.05,404.16,553.45,398.89,21.60,5.27,979.21
1,Feb-15,578.75,408.55,557.27,403.31,21.48,5.24,987.30
2,Mar-15,577.18,419.31,555.71,414.18,21.47,5.12,996.49
3,Apr-15,580.13,419.58,558.78,414.57,21.36,5.01,999.71
4,May-15,580.15,421.90,558.83,416.95,21.32,4.95,1002.05

In [148]:
df_connection.info()
print("""
    -----------------
    -----------------
""")
df_datafile.info()
print("""
    -----------------
    -----------------
""")
df_rbi.info()
print("""
    -----------------
    -----------------
""")
df_telecom_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sr.no                15 non-null     float64
 1   telecom_circle       16 non-null     object
 2   rural_exchanges      15 non-null     float64
 3   connection_provided  15 non-null     float64
dtypes: float64(3), object(1)
memory usage: 708.0+ bytes

    -----------------
    -----------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Columns: 136 entries, States/UTs to Men age 15 years and above who consume alcohol (%)
dtypes: float64(25), int64(3), object(108)
memory usage: 117.0+ KB

    -----------------
    -----------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sr no                               50 non-null     int64
 1   Number of transaction               50 non-null     int64
 2   Date                                50 non-null     datetime64[ns]
 3   Onsite_ATMs                         50 non-null     int64
 4   Offsite_ATMs                        50 non-null     int64
 5   PoS_Terminals                       50 non-null     int64
 6   Micro_ATMs                          50 non-null     int64
 7   Bharat_QR_Codes                     50 non-null     int64
 8   UPI_QR_Codes                        50 non-null     int64
 9   Credit_Cards_Outstanding            50 non-null     int64
 10  Debit_Cards_Outstanding             50 non-null     int64
 11  CC_PoS_Volume                       50 non-null     int64
 12  CC_PoS_Value_000Rs                  50 non-null     int64
 13  DC_PoS_Value_000Rs                  50 non-null     int64
 14  DC_Ecommerce_Volume                 50 non-null     int64
 15  DC_Ecommerce_Value_000Rs            50 non-null     int64
 16  DC_Other_Volume                     50 non-null     int64
 17  DC_Other_Value_000Rs                50 non-null     int64
 18  DC_ATM_Withdrawal_Volume            50 non-null     int64
 19  DC_ATM_Withdrawal_Value_000Rs       50 non-null     int64
 20  DC_PoS_Cash_Withdrawal_Volume       50 non-null     int64
 21  DC_PoS_Cash_Withdrawal_Value_000Rs  50 non-null     int64
dtypes: datetime64[ns](1), int64(21)
memory usage: 8.7 KB

    -----------------
    -----------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            132 non-null    object
 1   Urban           132 non-null    float64
 2   Rural           132 non-null    float64
 3   Urban_Wireless  132 non-null    float64
 4   Rural_Wireless  132 non-null    float64
 5   Urban_Wireline  132 non-null    float64
 6   Rural_Wireline  132 non-null    float64
 7   Total(million)  132 non-null    float64
dtypes: float64(7), object(1)
memory usage: 8.4+ KB

In [149]:
df_connection.columns.str.strip()
df_datafile.columns.str.strip()
df_rbi.columns.str.strip()
df_telecom_sub.columns.str.strip()

Index(['date', 'Urban', 'Rural', 'Urban_Wireless', 'Rural_Wireless',
       'Urban_Wireline', 'Rural_Wireline', 'Total(million)'],
      dtype='object')

# 1. Data Cleaing on RBI Dataset

In [150]:
df_rbi.columns

Index(['Sr no', 'Number of transaction', 'Date', 'Onsite_ATMs', 'Offsite_ATMs',
       'PoS_Terminals', 'Micro_ATMs', 'Bharat_QR_Codes', 'UPI_QR_Codes',
       'Credit_Cards_Outstanding', 'Debit_Cards_Outstanding', 'CC_PoS_Volume',
       'CC_PoS_Value_000Rs', 'DC_PoS_Value_000Rs', 'DC_Ecommerce_Volume',
       'DC_Ecommerce_Value_000Rs', 'DC_Other_Volume', 'DC_Other_Value_000Rs',
       'DC_ATM_Withdrawal_Volume', 'DC_ATM_Withdrawal_Value_000Rs',
       'DC_PoS_Cash_Withdrawal_Volume', 'DC_PoS_Cash_Withdrawal_Value_000Rs'],
      dtype='object')

In [151]:
df_rbi["Date"] = pd.to_datetime(df_rbi["Date"])

In [152]:
value_col = ['CC_PoS_Value_000Rs', 'DC_PoS_Value_000Rs', "DC_Ecommerce_Value_000Rs", "DC_Other_Value_000Rs", "DC_ATM_Withdrawal_Value_000Rs", "DC_PoS_Cash_Withdrawal_Value_000Rs"]

# Convert values to numeric
df_rbi[value_col] = df_rbi[value_col].apply(pd.to_numeric, errors='coerce')
# Convert ₹000 to ₹ Crore
df_rbi[value_col] = df_rbi[value_col] / 10_000

In [153]:
df_rbi[value_col].head()

,CC_PoS_Value_000Rs,DC_PoS_Value_000Rs,DC_Ecommerce_Value_000Rs,DC_Other_Value_000Rs,DC_ATM_Withdrawal_Value_000Rs,DC_PoS_Cash_Withdrawal_Value_000Rs
0,73848.8494,24343.4366,12465.1148,168.2311,231206.2478,1.5112
1,78470.4542,24346.4508,13433.9503,167.9903,248419.0349,1.7029
2,67435.4050,21861.7996,11109.9285,162.8965,230241.7305,1.6749
3,75987.8304,25513.0179,12279.0555,164.6178,239172.0254,0.1900
4,78476.4839,24599.0962,12512.3230,162.9609,238924.8011,1.9589

In [154]:
value_col = ['CC_PoS_Value_000Rs', 'DC_PoS_Value_000Rs', "DC_Ecommerce_Value_000Rs", "DC_Other_Value_000Rs", "DC_ATM_Withdrawal_Value_000Rs", "DC_PoS_Cash_Withdrawal_Value_000Rs"]
new_name = ['CC_PoS_Value_Crore', 'DC_PoS_Value_Crore', "DC_Ecommerce_Value_Crore", "DC_Other_Value_Crore", "DC_ATM_Withdrawal_Value_Crore", "DC_PoS_Cash_Withdrawal_Value_Crore"]

df_rbi = df_rbi.rename(columns=dict(zip(value_col, new_name)))
df_rbi.head()

,Sr no,Number of transaction,Date,Onsite_ATMs,Offsite_ATMs,PoS_Terminals,Micro_ATMs,Bharat_QR_Codes,UPI_QR_Codes,Credit_Cards_Outstanding,...,CC_PoS_Value_Crore,DC_PoS_Value_Crore,DC_Ecommerce_Volume,DC_Ecommerce_Value_Crore,DC_Other_Volume,DC_Other_Value_Crore,DC_ATM_Withdrawal_Volume,DC_ATM_Withdrawal_Value_Crore,DC_PoS_Cash_Withdrawal_Volume,DC_PoS_Cash_Withdrawal_Value_Crore
0,1,63,2026-04-01,136126,73857,11446998,1367989,5616038,770811461,119436129,...,73848.8494,24343.4366,25662638,12465.1148,74041,168.2311,413006692,231206.2478,8094,1.5112
1,2,64,2026-03-01,135638,73693,11769361,1389878,5633027,761217394,118633677,...,78470.4542,24346.4508,26307005,13433.9503,78017,167.9903,443999321,248419.0349,9984,1.7029
2,3,64,2026-02-01,135004,73830,11664877,1389518,5897360,754203742,117704486,...,67435.4050,21861.7996,22661665,11109.9285,73930,162.8965,414511705,230241.7305,10737,1.6749
3,4,64,2026-01-01,134085,73830,11545210,1391526,5843742,738380380,116652407,...,75987.8304,25513.0179,24429856,12279.0555,80114,164.6178,441200393,239172.0254,12351,0.1900
4,5,64,2025-12-01,133729,73756,11474672,1414547,5890220,731365285,115791713,...,78476.4839,24599.0962,25407654,12512.3230,81047,162.9609,444401793,238924.8011,11876,1.9589

# 2. Data Cleaing on TRAI Telecom

### 1. to datetime

In [155]:
df_telecom_sub["date"] = pd.to_datetime(
    df_telecom_sub["date"],
    format="%b-%y"
)

### 2.	Verify math integrity: Total = Urban + Rural and Urban = Urban_Wireless + Urban_Wireline.

In [156]:
columns = df_telecom_sub.drop(columns=["date", "Total(million)"])

In [157]:
columns["urban"] = columns["Urban_Wireless"] + columns["Urban_Wireline"] 
columns["rural"] = columns["Rural_Wireless"] + columns["Rural_Wireline"] 
columns["total"] = columns["Urban"] + columns["Rural"]

In [158]:
pd.concat([
    columns[["total", "urban", "rural"]].reset_index(drop=True),
    df_telecom_sub[["Total(million)", "Urban", "Rural"]].reset_index(drop=True)
], axis=1).head(10)

     total   urban   rural  Total(million)   Urban   Rural
0   979.21  575.05  404.16          979.21  575.05  404.16
1   987.30  578.75  408.55          987.30  578.75  408.55
2   996.49  577.18  419.30          996.49  577.18  419.31
3   999.71  580.14  419.58          999.71  580.13  419.58
4  1002.05  580.15  421.90         1002.05  580.15  421.90
5  1009.31  588.53  420.78         1009.31  588.53  420.78
6  1014.70  591.53  423.18         1014.70  591.52  423.18
7  1022.62  599.00  423.61         1022.61  599.01  423.61
8  1029.34  599.25  430.09         1029.34  599.25  430.09
9  1035.18  598.92  436.25         1035.18  598.92  436.26

# 3. Data Cleaing on NFHS-5 Factsheet

In [159]:
columns_to_keep = [
        'States/UTs',
        'Area',
        'Number of Households surveyed',
        'Population living in households with electricity (%)',
        'Households using clean fuel for cooking3 (%)',
        'Women (age 15-49) who are literate4 (%)',
        'Men (age 15-49) who are literate4 (%)',
        'Women (age 15-49)  with 10 or more years of schooling (%)',
        'Men (age 15-49)  with 10 or more years of schooling (%)',
        'Women (age 15-49)  who have ever used the internet (%)',
        'Men (age 15-49)  who have ever used the internet (%)',
        'Women (age 15-49 years) having a bank or savings account that they themselves use (%)',
        'Women (age 15-49 years) having a mobile phone that they themselves use (%)',
        'Currently married women (age 15-49 years) who usually participate in three household decisions25 (%)'
    ]
df_datafile = df_datafile[columns_to_keep]

In [160]:
df_datafile.head()

,States/UTs,Area,Number of Households surveyed,Population living in households with electricity (%),Households using clean fuel for cooking3 (%),Women (age 15-49) who are literate4 (%),Men (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Men (age 15-49) with 10 or more years of schooling (%),Women (age 15-49) who have ever used the internet (%),Men (age 15-49) who have ever used the internet (%),Women (age 15-49 years) having a bank or savings account that they themselves use (%),Women (age 15-49 years) having a mobile phone that they themselves use (%),Currently married women (age 15-49 years) who usually participate in three household decisions25 (%)
0,India,Urban,160138,99.1,89.7,83.0,89.6,56.3,62.1,51.8,72.5,80.9,69.4,91
1,India,Rural,476561,95.7,43.2,65.9,81.5,33.7,43.7,24.6,48.7,77.4,46.6,87.7
2,India,Total,636699,96.8,58.6,71.5,84.4,41.0,50.2,33.3,57.1,78.6,54,88.7
3,Andaman & Nicobar Islands,Urban,527,99.5,95.6,86.6,89.3,59.7,59.4,44.1,54.6,88.5,80.8,93
4,Andaman & Nicobar Islands,Rural,2097,96.5,71,85.6,94.7,47.6,47.7,27.9,41.1,89.8,80.9,95.5

### 1. Rename Columns

In [161]:
num_cols = df_datafile.columns[2:]
for c in num_cols:
    df_datafile[c] = pd.to_numeric(df_datafile[c].astype(str).str.strip().replace({'*': np.nan, '-': np.nan, '': np.nan}), errors='coerce')

In [162]:
columns_to_keep = [
        'States/UTs',
        'Households using clean fuel for cooking3 (%)',

        'Women (age 15-49) who are literate4 (%)',
        'Men (age 15-49) who are literate4 (%)',

        'Women (age 15-49)  with 10 or more years of schooling (%)',
        'Men (age 15-49)  with 10 or more years of schooling (%)',

        'Women (age 15-49)  who have ever used the internet (%)',
        'Men (age 15-49)  who have ever used the internet (%)',

        'Women (age 15-49 years) having a bank or savings account that they themselves use (%)',
        'Women (age 15-49 years) having a mobile phone that they themselves use (%)',

        'Population living in households with electricity (%)',
        'Currently married women (age 15-49 years) who usually participate in three household decisions25 (%)',
        'Number of Households surveyed',
    ]

to_rename = [
    "state_ut",
    "households_clean_fuel_pct",
    
    "female_literacy_pct",
    "male_literacy_pct",

    "female_schooling_pct",
    "male_schooling_pct",
    
    "Women_Internet_pct", 
    "Men_Internet_pct", 
    
    "women_bank_account_pct", 
    "Women_Mobile_Ownership_pct", 
    
    "Electricity_Access",
    "women_household_decisions_pct",
    "households_surveyed"
]
df_data = df_datafile.copy()

df_data = df_data.rename(
    columns=dict(zip(columns_to_keep, to_rename))
)

In [163]:
df_data.head()

,state_ut,Area,households_surveyed,Electricity_Access,households_clean_fuel_pct,female_literacy_pct,male_literacy_pct,female_schooling_pct,male_schooling_pct,Women_Internet_pct,Men_Internet_pct,women_bank_account_pct,Women_Mobile_Ownership_pct,women_household_decisions_pct
0,India,Urban,160138,99.1,89.7,83.0,89.6,56.3,62.1,51.8,72.5,80.9,69.4,91.0
1,India,Rural,476561,95.7,43.2,65.9,81.5,33.7,43.7,24.6,48.7,77.4,46.6,87.7
2,India,Total,636699,96.8,58.6,71.5,84.4,41.0,50.2,33.3,57.1,78.6,54.0,88.7
3,Andaman & Nicobar Islands,Urban,527,99.5,95.6,86.6,89.3,59.7,59.4,44.1,54.6,88.5,80.8,93.0
4,Andaman & Nicobar Islands,Rural,2097,96.5,71.0,85.6,94.7,47.6,47.7,27.9,41.1,89.8,80.9,95.5

In [164]:
col = [
    "households_clean_fuel_pct",
    "female_literacy_pct",
    "male_literacy_pct",
    "female_schooling_pct",
    "male_schooling_pct",
    "Women_Internet_pct", 
    "Men_Internet_pct", 
    "women_bank_account_pct", 
    "Women_Mobile_Ownership_pct",
    "women_household_decisions_pct",
]
for i in col:
    df_data[i].astype("float64")

In [165]:
float_cols = df_data.select_dtypes(include=['float64']).columns

# 2. Apply the absolute value function to just those columns
df_data[float_cols] = df_data[float_cols].abs()

### 2. Pivoting & Base Table Construction

In [166]:
df_total = df_data[df_datafile['Area'] == 'Total'].copy()
df_rural = df_data[df_datafile['Area'] == 'Rural'].copy()
df_urban = df_data[df_datafile['Area'] == 'Urban'].copy()

In [167]:
# Remove area column
df_total = df_total.drop(columns='Area')
df_rural = df_rural.drop(columns='Area')
df_urban = df_urban.drop(columns='Area')

In [168]:
# Add area suffix
df_total = df_total.rename(
    columns=lambda x: x if x == 'state_ut' else f'{x}_total'
)

df_rural = df_rural.rename(
    columns=lambda x: x if x == 'state_ut' else f'{x}_rural'
)

df_urban = df_urban.rename(
    columns=lambda x: x if x == 'state_ut' else f'{x}_urban'
)

In [169]:
df_master = (
    df_total
    .merge(df_rural, on='state_ut', how='inner')
    .merge(df_urban, on='state_ut', how='inner')
)

In [170]:
df_master.sort_values(by="households_surveyed_total").head()

,state_ut,households_surveyed_total,Electricity_Access_total,households_clean_fuel_pct_total,female_literacy_pct_total,male_literacy_pct_total,female_schooling_pct_total,male_schooling_pct_total,Women_Internet_pct_total,Men_Internet_pct_total,...,households_clean_fuel_pct_urban,female_literacy_pct_urban,male_literacy_pct_urban,female_schooling_pct_urban,male_schooling_pct_urban,Women_Internet_pct_urban,Men_Internet_pct_urban,women_bank_account_pct_urban,Women_Mobile_Ownership_pct_urban,women_household_decisions_pct_urban
6,Chandigarh,761,99.9,95.8,83.0,94.8,59.6,64.5,75.2,91.9,...,95.8,83.1,94.8,59.9,64.5,75.2,91.9,87.1,70.0,94.6
18,Lakshadweep,921,99.8,59.4,96.5,99.1,67.8,80.9,56.4,80.3,...,68.5,96.4,100.0,68.2,84.9,61.8,81.5,66.9,85.1,91.9
17,Ladakh,1818,99.5,76.3,76.8,93.7,50.0,72.7,56.4,67.8,...,97.2,77.7,91.9,53.8,64.1,66.5,82.9,87.2,80.8,81.2
9,Goa,1856,100.0,96.5,93.0,96.3,71.5,76.6,73.7,82.9,...,98.8,92.6,94.9,73.0,75.0,78.1,86.1,85.1,94.5,89.3
1,Andaman & Nicobar Islands,2624,97.6,79.8,86.0,92.5,52.5,52.3,34.8,46.5,...,95.6,86.6,89.3,59.7,59.4,44.1,54.6,88.5,80.8,93.0

# 4 Data Cleaning on Connection

In [171]:
df_connection = df_connection.dropna()

In [172]:
df_connection = df_connection.replace("A & N", "Andaman & Nicobar")

In [173]:
df_connection

    sr.no             telecom_circle  rural_exchanges  connection_provided
0     1.0          Andaman & Nicobar             45.0                405.0
1     2.0  Andhra Pradesh/ Telangana           2665.0              59647.0
2     3.0                      Assam            429.0               5067.0
3     4.0                      Bihar           1000.0               6817.0
4     5.0               Chhattisgarh            449.0               6743.0
5     6.0                    Chennai            123.0               5230.0
6     7.0                    Gujarat           1988.0              34315.0
7     8.0                    Haryana            805.0              21012.0
8     9.0           Himachal Pradesh            811.0               8188.0
9    10.0            Jammu & Kashmir            209.0               3057.0
10   11.0                  Jharkhand            291.0               3872.0
11   12.0                  Karnataka           2217.0              20464.0
12   13.0                     Kerala           1143.0             228741.0
13   14.0             Madhya Pradesh           1982.0              25216.0
14   15.0                Maharashtra           4353.0              44200.0

In [174]:
df_connection.to_csv("../dataset/clean/connection.csv", index=False)
df_master.to_csv("../dataset/clean/nfhs.csv", index=False)
df_telecom_sub.to_csv("../dataset/clean/telecom_sub.csv", index=False)
df_rbi.to_csv("../dataset/clean/rbi.csv", index=False)